In [0]:
import tensorflow as tf

In [0]:
x = tf.placeholder(tf.float32,shape=[None,32,32,3])
y_true = tf.placeholder(tf.float32,shape=[None,10])

In [0]:
hold_prob = tf.placeholder(tf.float32)

In [0]:
## creating 1st convolutional layer 

In [0]:
init_random_dist = tf.truncated_normal([4,4,3,32], stddev=0.1)
W=tf.Variable(init_random_dist)

init_bias_vals = tf.constant(0.1, shape=[[4,4,3,32][3]])
b=tf.Variable(init_bias_vals)

convo_1=tf.nn.conv2d(x, W, strides=[1, 1, 1, 1], padding='SAME')

convo_1=tf.nn.relu(convo_1 + b)

convo_1_pooling=tf.nn.max_pool(convo_1, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding='SAME')

In [0]:
## creating 2st convolutional layer 

In [0]:
init_random_dist = tf.truncated_normal([4,4,32,64], stddev=0.1)
W=tf.Variable(init_random_dist)

init_bias_vals = tf.constant(0.1, shape=[[4,4,32,64][3]])
b=tf.Variable(init_bias_vals)

convo_2=tf.nn.conv2d(convo_1_pooling, W, strides=[1, 1, 1, 1], padding='SAME')

convo_2=tf.nn.relu(convo_2 + b)

convo_2_pooling=tf.nn.max_pool(convo_2, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding='SAME')

In [0]:
convo_2_flat = tf.reshape(convo_2_pooling,[-1,8*8*64])

In [0]:
input_size = int(convo_2_flat.get_shape()[1])

init_random_dist = tf.truncated_normal([input_size,1024], stddev=0.1)
W=tf.Variable(init_random_dist)

init_bias_vals = tf.constant(0.1, shape=[1024])
b=tf.Variable(init_bias_vals)

full_layer_one=tf.nn.relu(tf.matmul(convo_2_flat, W) + b)

In [0]:
full_one_dropout = tf.nn.dropout(full_layer_one,keep_prob=hold_prob)

In [0]:
input_size = int(full_one_dropout.get_shape()[1])

init_random_dist = tf.truncated_normal([input_size,10], stddev=0.1)
W=tf.Variable(init_random_dist)

init_bias_vals = tf.constant(0.1, shape=[10])
b=tf.Variable(init_bias_vals)
y_pred=tf.matmul(full_one_dropout, W) + b

In [43]:
cross_entropy = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=y_true,logits=y_pred))

Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.



In [0]:
optimizer = tf.train.AdamOptimizer(learning_rate=0.001)
train = optimizer.minimize(cross_entropy)

In [0]:
init = tf.global_variables_initializer()

In [0]:
def unpickle(file):
    import pickle
    with open(file, 'rb') as fo:
        cifar_dict = pickle.load(fo, encoding='bytes')
    return cifar_dict
    

In [51]:
from google.colab import drive
drive.mount('/content/gdrive')


Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:

CIFAR_DIR = '/content/gdrive/My Drive/Colab Notebooks/Data_sets/cifar-10-batches-py/'
dirs = ['batches.meta','data_batch_1','data_batch_2','data_batch_3','data_batch_4','data_batch_5','test_batch']

In [0]:
all_data = [0,1,2,3,4,5,6]

In [50]:
for i,direc in zip(all_data,dirs):
  print(direc)

batches.meta
data_batch_1
data_batch_2
data_batch_3
data_batch_4
data_batch_5
test_batch


In [0]:
for i,direc in zip(all_data,dirs):
    all_data[i] = unpickle(CIFAR_DIR+direc)

In [0]:
all_data[1]

In [0]:
batch_meta = all_data[0]
data_batch1 = all_data[1]
data_batch2 = all_data[2]
data_batch3 = all_data[3]
data_batch4 = all_data[4]
data_batch5 = all_data[5]
test_batch = all_data[6]

In [0]:
X = data_batch1[b"data"] 

In [59]:
X

array([[ 59,  43,  50, ..., 140,  84,  72],
       [154, 126, 105, ..., 139, 142, 144],
       [255, 253, 253, ...,  83,  83,  84],
       ...,
       [ 71,  60,  74, ...,  68,  69,  68],
       [250, 254, 211, ..., 215, 255, 254],
       [ 62,  61,  60, ..., 130, 130, 131]], dtype=uint8)

In [0]:
import matplotlib.pyplot as plt
%matplotlib inline

X_re=X.reshape(10000, 3, 32, 32)



In [81]:
#plt.imshow(X_re[0])
X_re

array([[[[ 59,  43,  50, ..., 158, 152, 148],
         [ 16,   0,  18, ..., 123, 119, 122],
         [ 25,  16,  49, ..., 118, 120, 109],
         ...,
         [208, 201, 198, ..., 160,  56,  53],
         [180, 173, 186, ..., 184,  97,  83],
         [177, 168, 179, ..., 216, 151, 123]],

        [[ 62,  46,  48, ..., 132, 125, 124],
         [ 20,   0,   8, ...,  88,  83,  87],
         [ 24,   7,  27, ...,  84,  84,  73],
         ...,
         [170, 153, 161, ..., 133,  31,  34],
         [139, 123, 144, ..., 148,  62,  53],
         [144, 129, 142, ..., 184, 118,  92]],

        [[ 63,  45,  43, ..., 108, 102, 103],
         [ 20,   0,   0, ...,  55,  50,  57],
         [ 21,   0,   8, ...,  50,  50,  42],
         ...,
         [ 96,  34,  26, ...,  70,   7,  20],
         [ 96,  42,  30, ...,  94,  34,  34],
         [116,  94,  87, ..., 140,  84,  72]]],


       [[[154, 126, 105, ...,  91,  87,  79],
         [140, 145, 125, ...,  96,  77,  71],
         [140, 139, 115, ..., 

In [0]:
import numpy as np 
a = np.zeros((16, 2))
  

In [76]:
a.reshape(4,2,2,2)

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])